name: Danger JS

on:
  pull_request:
    types: [opened, reopened, syncronize, edited]

jobs:
  dangerjs:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Record before stats
        continue-on-error: true
        run: |
          mkdir -p .diff/audit-ci
          yarn install --immutable
          yarn dlx -q audit-ci@\^6 --config ./audit-ci.jsonc -o json > .diff/audit-ci/before.json

      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Record after stats
        continue-on-error: true
        run: |
          yarn install --immutable
          yarn dlx -q audit-ci@\^6 --config ./audit-ci.jsonc -o json > .diff/audit-ci/after.json

      - name: âš™ï¸ ESLint
        continue-on-error: true
        run: yarn lint:report

      - name: ğŸš¨ DangerJS
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}